<?php
$request = Agl::getRequest();

$this->setTitlePrefix("AGL Application");
$this->setTitleSeparator(' | ');

$this->setDescription("Meta description");
$this->setKeywords("Meta keywords");

$this->addMeta('charset', array(
    'charset' => 'utf-8'
));

$this->addMeta('http-equiv', array(
    'http-equiv' => 'X-UA-Compatible',
    'content'    => 'IE=edge,chrome=1'
));

$this->addMeta('viewport', array(
    'name'    => 'viewport',
    'content' => 'width=device-width'
));
?>
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <title><?php echo $this->getTitle() ?></title>
        <script>
            var baseUrl    = '<?php echo Url::getBase(false) ?>';
            var publicUrl  = '<?php echo Url::getPublic('', false) ?>';
            var skinUrl    = '<?php echo Url::getSkin('', false) ?>';
            var basePath   = '<?php echo Url::getBase() ?>';
            var publicPath = '<?php echo Url::getPublic('') ?>';
            var skinPath   = '<?php echo Url::getSkin('') ?>';
        </script>
        <?php
        echo $this->getMeta();
        echo $this->getCss();
        echo $this->getJs();
        ?>
    </head>
    <body class="<?php echo $request->getModule() . ' ' . $request->getModule() . '-' . $request->getView() . ' ' . $request->getModule() . '-' . $request->getView() . '-' . $request->getAction() ?>">
        <!--[if lt IE 7]>
            <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
        <![endif]-->

        <?php
        echo $this->getView();
        ?>

        <script>window.jQuery || document.write('<script src="<?php echo Url::getSkin('js/vendor/jquery-1.9.1.min.js') ?>"><\/script>')</script>

        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
        <script>
            var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
            (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
            g.src='//www.google-analytics.com/ga.js';
            s.parentNode.insertBefore(g,s)}(document,'script'));
        </script>
    </body>
</html>
