<?php
$request = Agl::getRequest();

$this->addMeta('charset', array(
    'charset' => 'utf-8'
));

$this->setTitlePrefix("AGL Application");
$this->setTitleSeparator(' | ');

$this->setDescription("Meta description");
$this->setKeywords("Meta keywords");

$this->addMeta('http-equiv', array(
    'http-equiv' => 'X-UA-Compatible',
    'content'    => 'IE=edge'
));

$this->addMeta('viewport', array(
    'name'    => 'viewport',
    'content' => 'width=device-width, initial-scale=1'
));
?>
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" itemscope itemtype="http://schema.org/"> <!--<![endif]-->
    <head>
        <title><?php echo $this->getTitle() ?></title>
        <?php
        echo $this->getMeta();
        ?>
        <script>
            var baseUrl    = '<?php echo Url::getBase(false) ?>';
            var publicUrl  = '<?php echo Url::getPublic('', false) ?>';
            var skinUrl    = '<?php echo Url::getSkin('', false) ?>';
            var basePath   = '<?php echo Url::getBase() ?>';
            var publicPath = '<?php echo Url::getPublic('') ?>';
            var skinPath   = '<?php echo Url::getSkin('') ?>';
        </script>
        <?php
        echo $this->getCss();
        echo $this->getJs();
        ?>
        <link rel="shortcut icon" type="image/x-icon" href="<?php echo Url::getSkin('images/favicon.ico') ?>" />
        <link rel="apple-touch-icon" sizes="144x144" href="<?php echo Url::getSkin('images/apple-touch-icon-precomposed.png') ?>" />
    </head>
    <body class="<?php echo $request->getModule() . ' ' . $request->getModule() . '-' . $request->getView() . ' ' . $request->getModule() . '-' . $request->getView() . '-' . $request->getAction() ?>">
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

        <?php
        echo $this->getView();
        ?>

        <script>window.jQuery || document.write('<script src="<?php echo Url::getSkin('js/vendor/jquery-1.10.2.min.js') ?>"><\/script>')</script>

        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
        <script>
            (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
            function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
            e=o.createElement(i);r=o.getElementsByTagName(i)[0];
            e.src='//www.google-analytics.com/analytics.js';
            r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
            ga('create','UA-XXXXX-X');ga('send','pageview');
        </script>
    </body>
</html>
