<?php
$this->setTitle("Home page");

// Display an alert if app/var is not writable.
$varDir = APP_PATH . Agl::APP_VAR_DIR;
if (! is_writable($varDir)) {
	?>
	<em><?php echo $varDir ?> is not writable</em>
	<?php
}
?>
<h1>Hello World!</h1>
<h2>This is the default AGL application</h2>
<p>This application is based on <a href="http://html5boilerplate.com/" target="_blank">HTML5 Boilerplate</a> v4.2.0, which includes:</p>
<ul>
	<li>Normalize.css v1.1.1</li>
	<li>Default HTML5 Boilerplate CSS</li>
	<li>jQuery v1.9.1 (loaded via Google CDN with a local fallback)</li>
	<li>Modernizr v2.6.2</li>
	<li>.htaccess optimizations</li>
</ul>
<p>The templates used by this page are:</p>
<ul>
	<li>app/template/main.phtml (main template structure)</li>
	<li>app/template/view/home/index.phtml (home page)</li>
</ul>
<p>Skin files (CSS, Images, JS) are in this directory:</p>
<ul>
	<li>public/skin/ (main CSS is public/skin/css/main.css)</li>
</ul>
<p>The location of the error pages are:</p>
<ul>
	<li>app/template/view/error/404.phtml (dynamic page, 404 error)</li>
	<li>public/error_static.phtml (static page, general error)</li>
</ul>
<p>Configuration files are located in those directories:</p>
<ul>
	<li>app/php/run.php (to enable Cache/Debug mode)</li>
	<li>app/etc/config/</li>
</ul>
<hr>
<p><a href="http://www.agl.io/doc/" target="_blank">Documentation</a>&nbsp;|&nbsp;<a href="http://www.agl.io/more/" target="_blank">Additional modules</a>&nbsp;|&nbsp;<a href="https://github.com/agl-php" target="_blank">GitHub</a>
