<?php
$this->setTitle("Home page");

// Display an alert if app/var is not writable.
$varDir = APP_PATH . Agl::APP_VAR_DIR;
if (! is_writable($varDir)) {
	?>
	<em><?php echo $varDir ?> is not writable</em>
	<?php
}
?>
<div>
	<a href="//agl.io/"><img src="<?php echo Url::getSkin('img/agl.png') ?>" width="102" height="89" alt="AGL Framework"></a>

	<ul>
		<li><a href="//agl.io/">Official website</a></li>
		<li><a href="//agl.io/doc/">Documentation</a></li>
		<li><a href="//github.com/agl-php/">GitHub</a></li>
	</ul>
</div>
