<?php
$this->setTitle("Home page");
?>
<h1>Hello World!</h1>
<h2>This is the default AGL application</h2>
<p>This application is based on <a href="http://html5boilerplate.com/">HTML5 Boilerplate</a> v4.0.2., which include:</p>
<ul>
	<li>Normalize.css v1.0.2</li>
	<li>HTML5 Boilerplate CSS</li>
	<li>jQuery v1.8.3 (loaded via Google CDN with a local fallback)</li>
	<li>Modernizr v2.6.2</li>
	<li>.htaccess optimizations</li>
</ul>
<p>The templates used by this page are:</p>
<ul>
	<li>app/template/default/default.phtml (main template structure)</li>
	<li>app/template/default/views/home/index.phtml (home page)</li>
</ul>
<p>The location of the error pages are:</p>
<ul>
	<li>404 page: app/template/default/views/errors/404.phtml</li>
	<li>General error page (static): public/error_static.phtml</li>
</ul>
<p>Configuration files are located in those directories:</p>
<ul>
	<li>app/php/run.php (path to AGL, Cache and Debug mode)</li>
	<li>app/etc/config/ (JSON configuration files)</li>
</ul>
<h2>Get started</h2>
<p>Routes, Layouts, Views, Blocks, Models, ACL, Cache, Session...<br>Learn how to create complete and complex applications with AGL by visiting the documentation: <a href="http://www.agl.io/doc/start">www.agl.io/doc/start</a></p>
<h2>Customize AGL</h2>
<p>I18n, Password Hashing, Mail, CSS/JS Minification, Cron Jobs...<br>Add more functionalities to your application by installing additional modules in a few minutes: <a href="http://www.agl.io/more/index">www.agl.io/more/index</a></p>
<hr>
<p><a href="http://www.agl.io/">Official Website</a>&nbsp;|&nbsp;<a href="http://www.agl.io/doc/start">Documentation</a>&nbsp;|&nbsp;<a href="https://github.com/agl-php">GitHub</a>
